//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3082.
// 
#pragma warning disable 1591

namespace bbIDLA.BBDiscussionBoardService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BBDiscussionBoardWebServicePortBinding", Namespace="http://bbdbws/")]
    public partial class BBDiscussionBoardWebServiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getConferenceDetailsForGivenConferenceBbIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback getGroupConferenceDetailsForGivenGroupBbIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCourseConferenceDetailsForGivenCourseIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback getAllGroupConferenceDetailsForGivenCourseIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback getAllTypesOfConferencesForGivenCourseIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback getForumDetailsForGivenConferenceBbIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback getTopLevelMessageForGivenForumBbIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback getImmediateChildMessagesForGivenMessageBbIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback getAllMessagesForGivenThreadInGivenForumBbIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback addMessageToGivenForumBbIdOrMessageBbIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteAllForumsInGivenConferenceBbIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteGivenForumAndSubThreadsOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteAllThreadsInGivenForumBbIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteMessageAndAllSubMessagesOperationCompleted;
        
        private System.Threading.SendOrPostCallback addForumToGivenConferenceBbIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback addConferenceOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteAllConferencesInGivenCourseBbIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteGivenConferenceAndSubForumsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BBDiscussionBoardWebServiceService() {
            this.Url = global::bbIDLA.Properties.Settings.Default.bbIDLA_BBDiscussionBoardService_BBDiscussionBoardWebServiceService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getConferenceDetailsForGivenConferenceBbIdCompletedEventHandler getConferenceDetailsForGivenConferenceBbIdCompleted;
        
        /// <remarks/>
        public event getGroupConferenceDetailsForGivenGroupBbIdCompletedEventHandler getGroupConferenceDetailsForGivenGroupBbIdCompleted;
        
        /// <remarks/>
        public event getCourseConferenceDetailsForGivenCourseIdCompletedEventHandler getCourseConferenceDetailsForGivenCourseIdCompleted;
        
        /// <remarks/>
        public event getAllGroupConferenceDetailsForGivenCourseIdCompletedEventHandler getAllGroupConferenceDetailsForGivenCourseIdCompleted;
        
        /// <remarks/>
        public event getAllTypesOfConferencesForGivenCourseIdCompletedEventHandler getAllTypesOfConferencesForGivenCourseIdCompleted;
        
        /// <remarks/>
        public event getForumDetailsForGivenConferenceBbIdCompletedEventHandler getForumDetailsForGivenConferenceBbIdCompleted;
        
        /// <remarks/>
        public event getTopLevelMessageForGivenForumBbIdCompletedEventHandler getTopLevelMessageForGivenForumBbIdCompleted;
        
        /// <remarks/>
        public event getImmediateChildMessagesForGivenMessageBbIdCompletedEventHandler getImmediateChildMessagesForGivenMessageBbIdCompleted;
        
        /// <remarks/>
        public event getAllMessagesForGivenThreadInGivenForumBbIdCompletedEventHandler getAllMessagesForGivenThreadInGivenForumBbIdCompleted;
        
        /// <remarks/>
        public event addMessageToGivenForumBbIdOrMessageBbIdCompletedEventHandler addMessageToGivenForumBbIdOrMessageBbIdCompleted;
        
        /// <remarks/>
        public event deleteAllForumsInGivenConferenceBbIdCompletedEventHandler deleteAllForumsInGivenConferenceBbIdCompleted;
        
        /// <remarks/>
        public event deleteGivenForumAndSubThreadsCompletedEventHandler deleteGivenForumAndSubThreadsCompleted;
        
        /// <remarks/>
        public event deleteAllThreadsInGivenForumBbIdCompletedEventHandler deleteAllThreadsInGivenForumBbIdCompleted;
        
        /// <remarks/>
        public event deleteMessageAndAllSubMessagesCompletedEventHandler deleteMessageAndAllSubMessagesCompleted;
        
        /// <remarks/>
        public event addForumToGivenConferenceBbIdCompletedEventHandler addForumToGivenConferenceBbIdCompleted;
        
        /// <remarks/>
        public event addConferenceCompletedEventHandler addConferenceCompleted;
        
        /// <remarks/>
        public event deleteAllConferencesInGivenCourseBbIdCompletedEventHandler deleteAllConferencesInGivenCourseBbIdCompleted;
        
        /// <remarks/>
        public event deleteGivenConferenceAndSubForumsCompletedEventHandler deleteGivenConferenceAndSubForumsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://bbdbws/", ResponseNamespace="http://bbdbws/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public stringArray[] getConferenceDetailsForGivenConferenceBbId([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string pwd, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string confBbId, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] bool headerDesc, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool headerDescSpecified) {
            object[] results = this.Invoke("getConferenceDetailsForGivenConferenceBbId", new object[] {
                        pwd,
                        confBbId,
                        headerDesc,
                        headerDescSpecified});
            return ((stringArray[])(results[0]));
        }
        
        /// <remarks/>
        public void getConferenceDetailsForGivenConferenceBbIdAsync(string pwd, string confBbId, bool headerDesc, bool headerDescSpecified) {
            this.getConferenceDetailsForGivenConferenceBbIdAsync(pwd, confBbId, headerDesc, headerDescSpecified, null);
        }
        
        /// <remarks/>
        public void getConferenceDetailsForGivenConferenceBbIdAsync(string pwd, string confBbId, bool headerDesc, bool headerDescSpecified, object userState) {
            if ((this.getConferenceDetailsForGivenConferenceBbIdOperationCompleted == null)) {
                this.getConferenceDetailsForGivenConferenceBbIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetConferenceDetailsForGivenConferenceBbIdOperationCompleted);
            }
            this.InvokeAsync("getConferenceDetailsForGivenConferenceBbId", new object[] {
                        pwd,
                        confBbId,
                        headerDesc,
                        headerDescSpecified}, this.getConferenceDetailsForGivenConferenceBbIdOperationCompleted, userState);
        }
        
        private void OngetConferenceDetailsForGivenConferenceBbIdOperationCompleted(object arg) {
            if ((this.getConferenceDetailsForGivenConferenceBbIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getConferenceDetailsForGivenConferenceBbIdCompleted(this, new getConferenceDetailsForGivenConferenceBbIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://bbdbws/", ResponseNamespace="http://bbdbws/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public stringArray[] getGroupConferenceDetailsForGivenGroupBbId([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string pwd, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string groupBbId, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] bool headerDesc, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool headerDescSpecified) {
            object[] results = this.Invoke("getGroupConferenceDetailsForGivenGroupBbId", new object[] {
                        pwd,
                        groupBbId,
                        headerDesc,
                        headerDescSpecified});
            return ((stringArray[])(results[0]));
        }
        
        /// <remarks/>
        public void getGroupConferenceDetailsForGivenGroupBbIdAsync(string pwd, string groupBbId, bool headerDesc, bool headerDescSpecified) {
            this.getGroupConferenceDetailsForGivenGroupBbIdAsync(pwd, groupBbId, headerDesc, headerDescSpecified, null);
        }
        
        /// <remarks/>
        public void getGroupConferenceDetailsForGivenGroupBbIdAsync(string pwd, string groupBbId, bool headerDesc, bool headerDescSpecified, object userState) {
            if ((this.getGroupConferenceDetailsForGivenGroupBbIdOperationCompleted == null)) {
                this.getGroupConferenceDetailsForGivenGroupBbIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetGroupConferenceDetailsForGivenGroupBbIdOperationCompleted);
            }
            this.InvokeAsync("getGroupConferenceDetailsForGivenGroupBbId", new object[] {
                        pwd,
                        groupBbId,
                        headerDesc,
                        headerDescSpecified}, this.getGroupConferenceDetailsForGivenGroupBbIdOperationCompleted, userState);
        }
        
        private void OngetGroupConferenceDetailsForGivenGroupBbIdOperationCompleted(object arg) {
            if ((this.getGroupConferenceDetailsForGivenGroupBbIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getGroupConferenceDetailsForGivenGroupBbIdCompleted(this, new getGroupConferenceDetailsForGivenGroupBbIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://bbdbws/", ResponseNamespace="http://bbdbws/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public stringArray[] getCourseConferenceDetailsForGivenCourseId([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string pwd, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string courseId, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] bool headerDesc, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool headerDescSpecified) {
            object[] results = this.Invoke("getCourseConferenceDetailsForGivenCourseId", new object[] {
                        pwd,
                        courseId,
                        headerDesc,
                        headerDescSpecified});
            return ((stringArray[])(results[0]));
        }
        
        /// <remarks/>
        public void getCourseConferenceDetailsForGivenCourseIdAsync(string pwd, string courseId, bool headerDesc, bool headerDescSpecified) {
            this.getCourseConferenceDetailsForGivenCourseIdAsync(pwd, courseId, headerDesc, headerDescSpecified, null);
        }
        
        /// <remarks/>
        public void getCourseConferenceDetailsForGivenCourseIdAsync(string pwd, string courseId, bool headerDesc, bool headerDescSpecified, object userState) {
            if ((this.getCourseConferenceDetailsForGivenCourseIdOperationCompleted == null)) {
                this.getCourseConferenceDetailsForGivenCourseIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCourseConferenceDetailsForGivenCourseIdOperationCompleted);
            }
            this.InvokeAsync("getCourseConferenceDetailsForGivenCourseId", new object[] {
                        pwd,
                        courseId,
                        headerDesc,
                        headerDescSpecified}, this.getCourseConferenceDetailsForGivenCourseIdOperationCompleted, userState);
        }
        
        private void OngetCourseConferenceDetailsForGivenCourseIdOperationCompleted(object arg) {
            if ((this.getCourseConferenceDetailsForGivenCourseIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCourseConferenceDetailsForGivenCourseIdCompleted(this, new getCourseConferenceDetailsForGivenCourseIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://bbdbws/", ResponseNamespace="http://bbdbws/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public stringArray[] getAllGroupConferenceDetailsForGivenCourseId([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string pwd, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string courseId, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] bool headerDesc, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool headerDescSpecified) {
            object[] results = this.Invoke("getAllGroupConferenceDetailsForGivenCourseId", new object[] {
                        pwd,
                        courseId,
                        headerDesc,
                        headerDescSpecified});
            return ((stringArray[])(results[0]));
        }
        
        /// <remarks/>
        public void getAllGroupConferenceDetailsForGivenCourseIdAsync(string pwd, string courseId, bool headerDesc, bool headerDescSpecified) {
            this.getAllGroupConferenceDetailsForGivenCourseIdAsync(pwd, courseId, headerDesc, headerDescSpecified, null);
        }
        
        /// <remarks/>
        public void getAllGroupConferenceDetailsForGivenCourseIdAsync(string pwd, string courseId, bool headerDesc, bool headerDescSpecified, object userState) {
            if ((this.getAllGroupConferenceDetailsForGivenCourseIdOperationCompleted == null)) {
                this.getAllGroupConferenceDetailsForGivenCourseIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAllGroupConferenceDetailsForGivenCourseIdOperationCompleted);
            }
            this.InvokeAsync("getAllGroupConferenceDetailsForGivenCourseId", new object[] {
                        pwd,
                        courseId,
                        headerDesc,
                        headerDescSpecified}, this.getAllGroupConferenceDetailsForGivenCourseIdOperationCompleted, userState);
        }
        
        private void OngetAllGroupConferenceDetailsForGivenCourseIdOperationCompleted(object arg) {
            if ((this.getAllGroupConferenceDetailsForGivenCourseIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAllGroupConferenceDetailsForGivenCourseIdCompleted(this, new getAllGroupConferenceDetailsForGivenCourseIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://bbdbws/", ResponseNamespace="http://bbdbws/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public stringArray[] getAllTypesOfConferencesForGivenCourseId([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string pwd, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string courseID, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] bool headerDesc, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool headerDescSpecified) {
            object[] results = this.Invoke("getAllTypesOfConferencesForGivenCourseId", new object[] {
                        pwd,
                        courseID,
                        headerDesc,
                        headerDescSpecified});
            return ((stringArray[])(results[0]));
        }
        
        /// <remarks/>
        public void getAllTypesOfConferencesForGivenCourseIdAsync(string pwd, string courseID, bool headerDesc, bool headerDescSpecified) {
            this.getAllTypesOfConferencesForGivenCourseIdAsync(pwd, courseID, headerDesc, headerDescSpecified, null);
        }
        
        /// <remarks/>
        public void getAllTypesOfConferencesForGivenCourseIdAsync(string pwd, string courseID, bool headerDesc, bool headerDescSpecified, object userState) {
            if ((this.getAllTypesOfConferencesForGivenCourseIdOperationCompleted == null)) {
                this.getAllTypesOfConferencesForGivenCourseIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAllTypesOfConferencesForGivenCourseIdOperationCompleted);
            }
            this.InvokeAsync("getAllTypesOfConferencesForGivenCourseId", new object[] {
                        pwd,
                        courseID,
                        headerDesc,
                        headerDescSpecified}, this.getAllTypesOfConferencesForGivenCourseIdOperationCompleted, userState);
        }
        
        private void OngetAllTypesOfConferencesForGivenCourseIdOperationCompleted(object arg) {
            if ((this.getAllTypesOfConferencesForGivenCourseIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAllTypesOfConferencesForGivenCourseIdCompleted(this, new getAllTypesOfConferencesForGivenCourseIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://bbdbws/", ResponseNamespace="http://bbdbws/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public stringArray[] getForumDetailsForGivenConferenceBbId([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string pwd, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string confBbIdD, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] bool headerDesc, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool headerDescSpecified) {
            object[] results = this.Invoke("getForumDetailsForGivenConferenceBbId", new object[] {
                        pwd,
                        confBbIdD,
                        headerDesc,
                        headerDescSpecified});
            return ((stringArray[])(results[0]));
        }
        
        /// <remarks/>
        public void getForumDetailsForGivenConferenceBbIdAsync(string pwd, string confBbIdD, bool headerDesc, bool headerDescSpecified) {
            this.getForumDetailsForGivenConferenceBbIdAsync(pwd, confBbIdD, headerDesc, headerDescSpecified, null);
        }
        
        /// <remarks/>
        public void getForumDetailsForGivenConferenceBbIdAsync(string pwd, string confBbIdD, bool headerDesc, bool headerDescSpecified, object userState) {
            if ((this.getForumDetailsForGivenConferenceBbIdOperationCompleted == null)) {
                this.getForumDetailsForGivenConferenceBbIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetForumDetailsForGivenConferenceBbIdOperationCompleted);
            }
            this.InvokeAsync("getForumDetailsForGivenConferenceBbId", new object[] {
                        pwd,
                        confBbIdD,
                        headerDesc,
                        headerDescSpecified}, this.getForumDetailsForGivenConferenceBbIdOperationCompleted, userState);
        }
        
        private void OngetForumDetailsForGivenConferenceBbIdOperationCompleted(object arg) {
            if ((this.getForumDetailsForGivenConferenceBbIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getForumDetailsForGivenConferenceBbIdCompleted(this, new getForumDetailsForGivenConferenceBbIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://bbdbws/", ResponseNamespace="http://bbdbws/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public stringArray[] getTopLevelMessageForGivenForumBbId([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string pwd, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string forumBbID, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] bool headerDesc, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool headerDescSpecified) {
            object[] results = this.Invoke("getTopLevelMessageForGivenForumBbId", new object[] {
                        pwd,
                        forumBbID,
                        headerDesc,
                        headerDescSpecified});
            return ((stringArray[])(results[0]));
        }
        
        /// <remarks/>
        public void getTopLevelMessageForGivenForumBbIdAsync(string pwd, string forumBbID, bool headerDesc, bool headerDescSpecified) {
            this.getTopLevelMessageForGivenForumBbIdAsync(pwd, forumBbID, headerDesc, headerDescSpecified, null);
        }
        
        /// <remarks/>
        public void getTopLevelMessageForGivenForumBbIdAsync(string pwd, string forumBbID, bool headerDesc, bool headerDescSpecified, object userState) {
            if ((this.getTopLevelMessageForGivenForumBbIdOperationCompleted == null)) {
                this.getTopLevelMessageForGivenForumBbIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetTopLevelMessageForGivenForumBbIdOperationCompleted);
            }
            this.InvokeAsync("getTopLevelMessageForGivenForumBbId", new object[] {
                        pwd,
                        forumBbID,
                        headerDesc,
                        headerDescSpecified}, this.getTopLevelMessageForGivenForumBbIdOperationCompleted, userState);
        }
        
        private void OngetTopLevelMessageForGivenForumBbIdOperationCompleted(object arg) {
            if ((this.getTopLevelMessageForGivenForumBbIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getTopLevelMessageForGivenForumBbIdCompleted(this, new getTopLevelMessageForGivenForumBbIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://bbdbws/", ResponseNamespace="http://bbdbws/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public stringArray[] getImmediateChildMessagesForGivenMessageBbId([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string pwd, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string messageBbId, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] bool headerDesc, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool headerDescSpecified) {
            object[] results = this.Invoke("getImmediateChildMessagesForGivenMessageBbId", new object[] {
                        pwd,
                        messageBbId,
                        headerDesc,
                        headerDescSpecified});
            return ((stringArray[])(results[0]));
        }
        
        /// <remarks/>
        public void getImmediateChildMessagesForGivenMessageBbIdAsync(string pwd, string messageBbId, bool headerDesc, bool headerDescSpecified) {
            this.getImmediateChildMessagesForGivenMessageBbIdAsync(pwd, messageBbId, headerDesc, headerDescSpecified, null);
        }
        
        /// <remarks/>
        public void getImmediateChildMessagesForGivenMessageBbIdAsync(string pwd, string messageBbId, bool headerDesc, bool headerDescSpecified, object userState) {
            if ((this.getImmediateChildMessagesForGivenMessageBbIdOperationCompleted == null)) {
                this.getImmediateChildMessagesForGivenMessageBbIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetImmediateChildMessagesForGivenMessageBbIdOperationCompleted);
            }
            this.InvokeAsync("getImmediateChildMessagesForGivenMessageBbId", new object[] {
                        pwd,
                        messageBbId,
                        headerDesc,
                        headerDescSpecified}, this.getImmediateChildMessagesForGivenMessageBbIdOperationCompleted, userState);
        }
        
        private void OngetImmediateChildMessagesForGivenMessageBbIdOperationCompleted(object arg) {
            if ((this.getImmediateChildMessagesForGivenMessageBbIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getImmediateChildMessagesForGivenMessageBbIdCompleted(this, new getImmediateChildMessagesForGivenMessageBbIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://bbdbws/", ResponseNamespace="http://bbdbws/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public stringArray[] getAllMessagesForGivenThreadInGivenForumBbId([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string pwd, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string threadTopLevelMessageBbId, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string forumBbId, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] bool headerDesc, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool headerDescSpecified) {
            object[] results = this.Invoke("getAllMessagesForGivenThreadInGivenForumBbId", new object[] {
                        pwd,
                        threadTopLevelMessageBbId,
                        forumBbId,
                        headerDesc,
                        headerDescSpecified});
            return ((stringArray[])(results[0]));
        }
        
        /// <remarks/>
        public void getAllMessagesForGivenThreadInGivenForumBbIdAsync(string pwd, string threadTopLevelMessageBbId, string forumBbId, bool headerDesc, bool headerDescSpecified) {
            this.getAllMessagesForGivenThreadInGivenForumBbIdAsync(pwd, threadTopLevelMessageBbId, forumBbId, headerDesc, headerDescSpecified, null);
        }
        
        /// <remarks/>
        public void getAllMessagesForGivenThreadInGivenForumBbIdAsync(string pwd, string threadTopLevelMessageBbId, string forumBbId, bool headerDesc, bool headerDescSpecified, object userState) {
            if ((this.getAllMessagesForGivenThreadInGivenForumBbIdOperationCompleted == null)) {
                this.getAllMessagesForGivenThreadInGivenForumBbIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAllMessagesForGivenThreadInGivenForumBbIdOperationCompleted);
            }
            this.InvokeAsync("getAllMessagesForGivenThreadInGivenForumBbId", new object[] {
                        pwd,
                        threadTopLevelMessageBbId,
                        forumBbId,
                        headerDesc,
                        headerDescSpecified}, this.getAllMessagesForGivenThreadInGivenForumBbIdOperationCompleted, userState);
        }
        
        private void OngetAllMessagesForGivenThreadInGivenForumBbIdOperationCompleted(object arg) {
            if ((this.getAllMessagesForGivenThreadInGivenForumBbIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAllMessagesForGivenThreadInGivenForumBbIdCompleted(this, new getAllMessagesForGivenThreadInGivenForumBbIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://bbdbws/", ResponseNamespace="http://bbdbws/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string addMessageToGivenForumBbIdOrMessageBbId([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string pwd, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string forumBbId, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string parentMessageBbId, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string subject, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string body) {
            object[] results = this.Invoke("addMessageToGivenForumBbIdOrMessageBbId", new object[] {
                        pwd,
                        forumBbId,
                        parentMessageBbId,
                        subject,
                        body});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void addMessageToGivenForumBbIdOrMessageBbIdAsync(string pwd, string forumBbId, string parentMessageBbId, string subject, string body) {
            this.addMessageToGivenForumBbIdOrMessageBbIdAsync(pwd, forumBbId, parentMessageBbId, subject, body, null);
        }
        
        /// <remarks/>
        public void addMessageToGivenForumBbIdOrMessageBbIdAsync(string pwd, string forumBbId, string parentMessageBbId, string subject, string body, object userState) {
            if ((this.addMessageToGivenForumBbIdOrMessageBbIdOperationCompleted == null)) {
                this.addMessageToGivenForumBbIdOrMessageBbIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddMessageToGivenForumBbIdOrMessageBbIdOperationCompleted);
            }
            this.InvokeAsync("addMessageToGivenForumBbIdOrMessageBbId", new object[] {
                        pwd,
                        forumBbId,
                        parentMessageBbId,
                        subject,
                        body}, this.addMessageToGivenForumBbIdOrMessageBbIdOperationCompleted, userState);
        }
        
        private void OnaddMessageToGivenForumBbIdOrMessageBbIdOperationCompleted(object arg) {
            if ((this.addMessageToGivenForumBbIdOrMessageBbIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addMessageToGivenForumBbIdOrMessageBbIdCompleted(this, new addMessageToGivenForumBbIdOrMessageBbIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://bbdbws/", ResponseNamespace="http://bbdbws/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string deleteAllForumsInGivenConferenceBbId([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string pwd, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string confBbId) {
            object[] results = this.Invoke("deleteAllForumsInGivenConferenceBbId", new object[] {
                        pwd,
                        confBbId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void deleteAllForumsInGivenConferenceBbIdAsync(string pwd, string confBbId) {
            this.deleteAllForumsInGivenConferenceBbIdAsync(pwd, confBbId, null);
        }
        
        /// <remarks/>
        public void deleteAllForumsInGivenConferenceBbIdAsync(string pwd, string confBbId, object userState) {
            if ((this.deleteAllForumsInGivenConferenceBbIdOperationCompleted == null)) {
                this.deleteAllForumsInGivenConferenceBbIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteAllForumsInGivenConferenceBbIdOperationCompleted);
            }
            this.InvokeAsync("deleteAllForumsInGivenConferenceBbId", new object[] {
                        pwd,
                        confBbId}, this.deleteAllForumsInGivenConferenceBbIdOperationCompleted, userState);
        }
        
        private void OndeleteAllForumsInGivenConferenceBbIdOperationCompleted(object arg) {
            if ((this.deleteAllForumsInGivenConferenceBbIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteAllForumsInGivenConferenceBbIdCompleted(this, new deleteAllForumsInGivenConferenceBbIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://bbdbws/", ResponseNamespace="http://bbdbws/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string deleteGivenForumAndSubThreads([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string pwd, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string forumBbId) {
            object[] results = this.Invoke("deleteGivenForumAndSubThreads", new object[] {
                        pwd,
                        forumBbId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void deleteGivenForumAndSubThreadsAsync(string pwd, string forumBbId) {
            this.deleteGivenForumAndSubThreadsAsync(pwd, forumBbId, null);
        }
        
        /// <remarks/>
        public void deleteGivenForumAndSubThreadsAsync(string pwd, string forumBbId, object userState) {
            if ((this.deleteGivenForumAndSubThreadsOperationCompleted == null)) {
                this.deleteGivenForumAndSubThreadsOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteGivenForumAndSubThreadsOperationCompleted);
            }
            this.InvokeAsync("deleteGivenForumAndSubThreads", new object[] {
                        pwd,
                        forumBbId}, this.deleteGivenForumAndSubThreadsOperationCompleted, userState);
        }
        
        private void OndeleteGivenForumAndSubThreadsOperationCompleted(object arg) {
            if ((this.deleteGivenForumAndSubThreadsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteGivenForumAndSubThreadsCompleted(this, new deleteGivenForumAndSubThreadsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://bbdbws/", ResponseNamespace="http://bbdbws/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string deleteAllThreadsInGivenForumBbId([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string pwd, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string forumBbId) {
            object[] results = this.Invoke("deleteAllThreadsInGivenForumBbId", new object[] {
                        pwd,
                        forumBbId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void deleteAllThreadsInGivenForumBbIdAsync(string pwd, string forumBbId) {
            this.deleteAllThreadsInGivenForumBbIdAsync(pwd, forumBbId, null);
        }
        
        /// <remarks/>
        public void deleteAllThreadsInGivenForumBbIdAsync(string pwd, string forumBbId, object userState) {
            if ((this.deleteAllThreadsInGivenForumBbIdOperationCompleted == null)) {
                this.deleteAllThreadsInGivenForumBbIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteAllThreadsInGivenForumBbIdOperationCompleted);
            }
            this.InvokeAsync("deleteAllThreadsInGivenForumBbId", new object[] {
                        pwd,
                        forumBbId}, this.deleteAllThreadsInGivenForumBbIdOperationCompleted, userState);
        }
        
        private void OndeleteAllThreadsInGivenForumBbIdOperationCompleted(object arg) {
            if ((this.deleteAllThreadsInGivenForumBbIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteAllThreadsInGivenForumBbIdCompleted(this, new deleteAllThreadsInGivenForumBbIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://bbdbws/", ResponseNamespace="http://bbdbws/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string deleteMessageAndAllSubMessages([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string pwd, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string messageBbId) {
            object[] results = this.Invoke("deleteMessageAndAllSubMessages", new object[] {
                        pwd,
                        messageBbId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void deleteMessageAndAllSubMessagesAsync(string pwd, string messageBbId) {
            this.deleteMessageAndAllSubMessagesAsync(pwd, messageBbId, null);
        }
        
        /// <remarks/>
        public void deleteMessageAndAllSubMessagesAsync(string pwd, string messageBbId, object userState) {
            if ((this.deleteMessageAndAllSubMessagesOperationCompleted == null)) {
                this.deleteMessageAndAllSubMessagesOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteMessageAndAllSubMessagesOperationCompleted);
            }
            this.InvokeAsync("deleteMessageAndAllSubMessages", new object[] {
                        pwd,
                        messageBbId}, this.deleteMessageAndAllSubMessagesOperationCompleted, userState);
        }
        
        private void OndeleteMessageAndAllSubMessagesOperationCompleted(object arg) {
            if ((this.deleteMessageAndAllSubMessagesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteMessageAndAllSubMessagesCompleted(this, new deleteMessageAndAllSubMessagesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://bbdbws/", ResponseNamespace="http://bbdbws/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string addForumToGivenConferenceBbId([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string pwd, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string confBbId, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string title, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string description, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string descType, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] bool available, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool availableSpecified) {
            object[] results = this.Invoke("addForumToGivenConferenceBbId", new object[] {
                        pwd,
                        confBbId,
                        title,
                        description,
                        descType,
                        available,
                        availableSpecified});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void addForumToGivenConferenceBbIdAsync(string pwd, string confBbId, string title, string description, string descType, bool available, bool availableSpecified) {
            this.addForumToGivenConferenceBbIdAsync(pwd, confBbId, title, description, descType, available, availableSpecified, null);
        }
        
        /// <remarks/>
        public void addForumToGivenConferenceBbIdAsync(string pwd, string confBbId, string title, string description, string descType, bool available, bool availableSpecified, object userState) {
            if ((this.addForumToGivenConferenceBbIdOperationCompleted == null)) {
                this.addForumToGivenConferenceBbIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddForumToGivenConferenceBbIdOperationCompleted);
            }
            this.InvokeAsync("addForumToGivenConferenceBbId", new object[] {
                        pwd,
                        confBbId,
                        title,
                        description,
                        descType,
                        available,
                        availableSpecified}, this.addForumToGivenConferenceBbIdOperationCompleted, userState);
        }
        
        private void OnaddForumToGivenConferenceBbIdOperationCompleted(object arg) {
            if ((this.addForumToGivenConferenceBbIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addForumToGivenConferenceBbIdCompleted(this, new addForumToGivenConferenceBbIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://bbdbws/", ResponseNamespace="http://bbdbws/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string addConference([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string pwd, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string courseId, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string groupBbId, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string conferenceType, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] bool available, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool availableSpecified, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string title, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string description) {
            object[] results = this.Invoke("addConference", new object[] {
                        pwd,
                        courseId,
                        groupBbId,
                        conferenceType,
                        available,
                        availableSpecified,
                        title,
                        description});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void addConferenceAsync(string pwd, string courseId, string groupBbId, string conferenceType, bool available, bool availableSpecified, string title, string description) {
            this.addConferenceAsync(pwd, courseId, groupBbId, conferenceType, available, availableSpecified, title, description, null);
        }
        
        /// <remarks/>
        public void addConferenceAsync(string pwd, string courseId, string groupBbId, string conferenceType, bool available, bool availableSpecified, string title, string description, object userState) {
            if ((this.addConferenceOperationCompleted == null)) {
                this.addConferenceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddConferenceOperationCompleted);
            }
            this.InvokeAsync("addConference", new object[] {
                        pwd,
                        courseId,
                        groupBbId,
                        conferenceType,
                        available,
                        availableSpecified,
                        title,
                        description}, this.addConferenceOperationCompleted, userState);
        }
        
        private void OnaddConferenceOperationCompleted(object arg) {
            if ((this.addConferenceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addConferenceCompleted(this, new addConferenceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://bbdbws/", ResponseNamespace="http://bbdbws/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string deleteAllConferencesInGivenCourseBbId([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string pwd, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string courseBbId) {
            object[] results = this.Invoke("deleteAllConferencesInGivenCourseBbId", new object[] {
                        pwd,
                        courseBbId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void deleteAllConferencesInGivenCourseBbIdAsync(string pwd, string courseBbId) {
            this.deleteAllConferencesInGivenCourseBbIdAsync(pwd, courseBbId, null);
        }
        
        /// <remarks/>
        public void deleteAllConferencesInGivenCourseBbIdAsync(string pwd, string courseBbId, object userState) {
            if ((this.deleteAllConferencesInGivenCourseBbIdOperationCompleted == null)) {
                this.deleteAllConferencesInGivenCourseBbIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteAllConferencesInGivenCourseBbIdOperationCompleted);
            }
            this.InvokeAsync("deleteAllConferencesInGivenCourseBbId", new object[] {
                        pwd,
                        courseBbId}, this.deleteAllConferencesInGivenCourseBbIdOperationCompleted, userState);
        }
        
        private void OndeleteAllConferencesInGivenCourseBbIdOperationCompleted(object arg) {
            if ((this.deleteAllConferencesInGivenCourseBbIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteAllConferencesInGivenCourseBbIdCompleted(this, new deleteAllConferencesInGivenCourseBbIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://bbdbws/", ResponseNamespace="http://bbdbws/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string deleteGivenConferenceAndSubForums([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string pwd, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string confBbId) {
            object[] results = this.Invoke("deleteGivenConferenceAndSubForums", new object[] {
                        pwd,
                        confBbId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void deleteGivenConferenceAndSubForumsAsync(string pwd, string confBbId) {
            this.deleteGivenConferenceAndSubForumsAsync(pwd, confBbId, null);
        }
        
        /// <remarks/>
        public void deleteGivenConferenceAndSubForumsAsync(string pwd, string confBbId, object userState) {
            if ((this.deleteGivenConferenceAndSubForumsOperationCompleted == null)) {
                this.deleteGivenConferenceAndSubForumsOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteGivenConferenceAndSubForumsOperationCompleted);
            }
            this.InvokeAsync("deleteGivenConferenceAndSubForums", new object[] {
                        pwd,
                        confBbId}, this.deleteGivenConferenceAndSubForumsOperationCompleted, userState);
        }
        
        private void OndeleteGivenConferenceAndSubForumsOperationCompleted(object arg) {
            if ((this.deleteGivenConferenceAndSubForumsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteGivenConferenceAndSubForumsCompleted(this, new deleteGivenConferenceAndSubForumsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://jaxb.dev.java.net/array")]
    public partial class stringArray {
        
        private string[] itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void getConferenceDetailsForGivenConferenceBbIdCompletedEventHandler(object sender, getConferenceDetailsForGivenConferenceBbIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getConferenceDetailsForGivenConferenceBbIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getConferenceDetailsForGivenConferenceBbIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public stringArray[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((stringArray[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void getGroupConferenceDetailsForGivenGroupBbIdCompletedEventHandler(object sender, getGroupConferenceDetailsForGivenGroupBbIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getGroupConferenceDetailsForGivenGroupBbIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getGroupConferenceDetailsForGivenGroupBbIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public stringArray[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((stringArray[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void getCourseConferenceDetailsForGivenCourseIdCompletedEventHandler(object sender, getCourseConferenceDetailsForGivenCourseIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCourseConferenceDetailsForGivenCourseIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCourseConferenceDetailsForGivenCourseIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public stringArray[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((stringArray[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void getAllGroupConferenceDetailsForGivenCourseIdCompletedEventHandler(object sender, getAllGroupConferenceDetailsForGivenCourseIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAllGroupConferenceDetailsForGivenCourseIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAllGroupConferenceDetailsForGivenCourseIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public stringArray[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((stringArray[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void getAllTypesOfConferencesForGivenCourseIdCompletedEventHandler(object sender, getAllTypesOfConferencesForGivenCourseIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAllTypesOfConferencesForGivenCourseIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAllTypesOfConferencesForGivenCourseIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public stringArray[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((stringArray[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void getForumDetailsForGivenConferenceBbIdCompletedEventHandler(object sender, getForumDetailsForGivenConferenceBbIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getForumDetailsForGivenConferenceBbIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getForumDetailsForGivenConferenceBbIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public stringArray[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((stringArray[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void getTopLevelMessageForGivenForumBbIdCompletedEventHandler(object sender, getTopLevelMessageForGivenForumBbIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getTopLevelMessageForGivenForumBbIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getTopLevelMessageForGivenForumBbIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public stringArray[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((stringArray[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void getImmediateChildMessagesForGivenMessageBbIdCompletedEventHandler(object sender, getImmediateChildMessagesForGivenMessageBbIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getImmediateChildMessagesForGivenMessageBbIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getImmediateChildMessagesForGivenMessageBbIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public stringArray[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((stringArray[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void getAllMessagesForGivenThreadInGivenForumBbIdCompletedEventHandler(object sender, getAllMessagesForGivenThreadInGivenForumBbIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAllMessagesForGivenThreadInGivenForumBbIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAllMessagesForGivenThreadInGivenForumBbIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public stringArray[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((stringArray[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void addMessageToGivenForumBbIdOrMessageBbIdCompletedEventHandler(object sender, addMessageToGivenForumBbIdOrMessageBbIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addMessageToGivenForumBbIdOrMessageBbIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addMessageToGivenForumBbIdOrMessageBbIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void deleteAllForumsInGivenConferenceBbIdCompletedEventHandler(object sender, deleteAllForumsInGivenConferenceBbIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteAllForumsInGivenConferenceBbIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteAllForumsInGivenConferenceBbIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void deleteGivenForumAndSubThreadsCompletedEventHandler(object sender, deleteGivenForumAndSubThreadsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteGivenForumAndSubThreadsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteGivenForumAndSubThreadsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void deleteAllThreadsInGivenForumBbIdCompletedEventHandler(object sender, deleteAllThreadsInGivenForumBbIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteAllThreadsInGivenForumBbIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteAllThreadsInGivenForumBbIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void deleteMessageAndAllSubMessagesCompletedEventHandler(object sender, deleteMessageAndAllSubMessagesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteMessageAndAllSubMessagesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteMessageAndAllSubMessagesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void addForumToGivenConferenceBbIdCompletedEventHandler(object sender, addForumToGivenConferenceBbIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addForumToGivenConferenceBbIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addForumToGivenConferenceBbIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void addConferenceCompletedEventHandler(object sender, addConferenceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addConferenceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addConferenceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void deleteAllConferencesInGivenCourseBbIdCompletedEventHandler(object sender, deleteAllConferencesInGivenCourseBbIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteAllConferencesInGivenCourseBbIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteAllConferencesInGivenCourseBbIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void deleteGivenConferenceAndSubForumsCompletedEventHandler(object sender, deleteGivenConferenceAndSubForumsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteGivenConferenceAndSubForumsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteGivenConferenceAndSubForumsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591