//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3649
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3649.
// 
#pragma warning disable 1591

namespace bbIDLA.BBContentService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BBContentWebServicePortBinding", Namespace="http://www.ncl.ac.uk/BBContentWebService")]
    public partial class BBContentWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback deleteContentByContentBbIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback getContentTocDetailsForGivenCourseOperationCompleted;
        
        private System.Threading.SendOrPostCallback getChildContentFromParentContentBbIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback getContentDetailsFromContentBbIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback getFileDetailsFromContentBbIdOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BBContentWebService() {
            this.Url = global::bbIDLA.Properties.Settings.Default.bbIDLA_BBContentService_BBContentWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event deleteContentByContentBbIdCompletedEventHandler deleteContentByContentBbIdCompleted;
        
        /// <remarks/>
        public event getContentTocDetailsForGivenCourseCompletedEventHandler getContentTocDetailsForGivenCourseCompleted;
        
        /// <remarks/>
        public event getChildContentFromParentContentBbIdCompletedEventHandler getChildContentFromParentContentBbIdCompleted;
        
        /// <remarks/>
        public event getContentDetailsFromContentBbIdCompletedEventHandler getContentDetailsFromContentBbIdCompleted;
        
        /// <remarks/>
        public event getFileDetailsFromContentBbIdCompletedEventHandler getFileDetailsFromContentBbIdCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://www.ncl.ac.uk/BBContentWebService", ResponseNamespace="http://www.ncl.ac.uk/BBContentWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string deleteContentByContentBbId([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string pwd, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string contentBbId) {
            object[] results = this.Invoke("deleteContentByContentBbId", new object[] {
                        pwd,
                        contentBbId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void deleteContentByContentBbIdAsync(string pwd, string contentBbId) {
            this.deleteContentByContentBbIdAsync(pwd, contentBbId, null);
        }
        
        /// <remarks/>
        public void deleteContentByContentBbIdAsync(string pwd, string contentBbId, object userState) {
            if ((this.deleteContentByContentBbIdOperationCompleted == null)) {
                this.deleteContentByContentBbIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteContentByContentBbIdOperationCompleted);
            }
            this.InvokeAsync("deleteContentByContentBbId", new object[] {
                        pwd,
                        contentBbId}, this.deleteContentByContentBbIdOperationCompleted, userState);
        }
        
        private void OndeleteContentByContentBbIdOperationCompleted(object arg) {
            if ((this.deleteContentByContentBbIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteContentByContentBbIdCompleted(this, new deleteContentByContentBbIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://www.ncl.ac.uk/BBContentWebService", ResponseNamespace="http://www.ncl.ac.uk/BBContentWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public stringArray[] getContentTocDetailsForGivenCourse([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string pwd, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string courseId, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] bool headerDesc, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool headerDescSpecified) {
            object[] results = this.Invoke("getContentTocDetailsForGivenCourse", new object[] {
                        pwd,
                        courseId,
                        headerDesc,
                        headerDescSpecified});
            return ((stringArray[])(results[0]));
        }
        
        /// <remarks/>
        public void getContentTocDetailsForGivenCourseAsync(string pwd, string courseId, bool headerDesc, bool headerDescSpecified) {
            this.getContentTocDetailsForGivenCourseAsync(pwd, courseId, headerDesc, headerDescSpecified, null);
        }
        
        /// <remarks/>
        public void getContentTocDetailsForGivenCourseAsync(string pwd, string courseId, bool headerDesc, bool headerDescSpecified, object userState) {
            if ((this.getContentTocDetailsForGivenCourseOperationCompleted == null)) {
                this.getContentTocDetailsForGivenCourseOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetContentTocDetailsForGivenCourseOperationCompleted);
            }
            this.InvokeAsync("getContentTocDetailsForGivenCourse", new object[] {
                        pwd,
                        courseId,
                        headerDesc,
                        headerDescSpecified}, this.getContentTocDetailsForGivenCourseOperationCompleted, userState);
        }
        
        private void OngetContentTocDetailsForGivenCourseOperationCompleted(object arg) {
            if ((this.getContentTocDetailsForGivenCourseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getContentTocDetailsForGivenCourseCompleted(this, new getContentTocDetailsForGivenCourseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://www.ncl.ac.uk/BBContentWebService", ResponseNamespace="http://www.ncl.ac.uk/BBContentWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public stringArray[] getChildContentFromParentContentBbId([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string pwd, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string parentContentBbId, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] bool headerDesc, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool headerDescSpecified) {
            object[] results = this.Invoke("getChildContentFromParentContentBbId", new object[] {
                        pwd,
                        parentContentBbId,
                        headerDesc,
                        headerDescSpecified});
            return ((stringArray[])(results[0]));
        }
        
        /// <remarks/>
        public void getChildContentFromParentContentBbIdAsync(string pwd, string parentContentBbId, bool headerDesc, bool headerDescSpecified) {
            this.getChildContentFromParentContentBbIdAsync(pwd, parentContentBbId, headerDesc, headerDescSpecified, null);
        }
        
        /// <remarks/>
        public void getChildContentFromParentContentBbIdAsync(string pwd, string parentContentBbId, bool headerDesc, bool headerDescSpecified, object userState) {
            if ((this.getChildContentFromParentContentBbIdOperationCompleted == null)) {
                this.getChildContentFromParentContentBbIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetChildContentFromParentContentBbIdOperationCompleted);
            }
            this.InvokeAsync("getChildContentFromParentContentBbId", new object[] {
                        pwd,
                        parentContentBbId,
                        headerDesc,
                        headerDescSpecified}, this.getChildContentFromParentContentBbIdOperationCompleted, userState);
        }
        
        private void OngetChildContentFromParentContentBbIdOperationCompleted(object arg) {
            if ((this.getChildContentFromParentContentBbIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getChildContentFromParentContentBbIdCompleted(this, new getChildContentFromParentContentBbIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://www.ncl.ac.uk/BBContentWebService", ResponseNamespace="http://www.ncl.ac.uk/BBContentWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public stringArray[] getContentDetailsFromContentBbId([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string pwd, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string contentId, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] bool headerDesc, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool headerDescSpecified) {
            object[] results = this.Invoke("getContentDetailsFromContentBbId", new object[] {
                        pwd,
                        contentId,
                        headerDesc,
                        headerDescSpecified});
            return ((stringArray[])(results[0]));
        }
        
        /// <remarks/>
        public void getContentDetailsFromContentBbIdAsync(string pwd, string contentId, bool headerDesc, bool headerDescSpecified) {
            this.getContentDetailsFromContentBbIdAsync(pwd, contentId, headerDesc, headerDescSpecified, null);
        }
        
        /// <remarks/>
        public void getContentDetailsFromContentBbIdAsync(string pwd, string contentId, bool headerDesc, bool headerDescSpecified, object userState) {
            if ((this.getContentDetailsFromContentBbIdOperationCompleted == null)) {
                this.getContentDetailsFromContentBbIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetContentDetailsFromContentBbIdOperationCompleted);
            }
            this.InvokeAsync("getContentDetailsFromContentBbId", new object[] {
                        pwd,
                        contentId,
                        headerDesc,
                        headerDescSpecified}, this.getContentDetailsFromContentBbIdOperationCompleted, userState);
        }
        
        private void OngetContentDetailsFromContentBbIdOperationCompleted(object arg) {
            if ((this.getContentDetailsFromContentBbIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getContentDetailsFromContentBbIdCompleted(this, new getContentDetailsFromContentBbIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://www.ncl.ac.uk/BBContentWebService", ResponseNamespace="http://www.ncl.ac.uk/BBContentWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public stringArray[] getFileDetailsFromContentBbId([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string pwd, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string contentBbId, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] bool headerDesc, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool headerDescSpecified) {
            object[] results = this.Invoke("getFileDetailsFromContentBbId", new object[] {
                        pwd,
                        contentBbId,
                        headerDesc,
                        headerDescSpecified});
            return ((stringArray[])(results[0]));
        }
        
        /// <remarks/>
        public void getFileDetailsFromContentBbIdAsync(string pwd, string contentBbId, bool headerDesc, bool headerDescSpecified) {
            this.getFileDetailsFromContentBbIdAsync(pwd, contentBbId, headerDesc, headerDescSpecified, null);
        }
        
        /// <remarks/>
        public void getFileDetailsFromContentBbIdAsync(string pwd, string contentBbId, bool headerDesc, bool headerDescSpecified, object userState) {
            if ((this.getFileDetailsFromContentBbIdOperationCompleted == null)) {
                this.getFileDetailsFromContentBbIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetFileDetailsFromContentBbIdOperationCompleted);
            }
            this.InvokeAsync("getFileDetailsFromContentBbId", new object[] {
                        pwd,
                        contentBbId,
                        headerDesc,
                        headerDescSpecified}, this.getFileDetailsFromContentBbIdOperationCompleted, userState);
        }
        
        private void OngetFileDetailsFromContentBbIdOperationCompleted(object arg) {
            if ((this.getFileDetailsFromContentBbIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getFileDetailsFromContentBbIdCompleted(this, new getFileDetailsFromContentBbIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3654")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://jaxb.dev.java.net/array")]
    public partial class stringArray {
        
        private string[] itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void deleteContentByContentBbIdCompletedEventHandler(object sender, deleteContentByContentBbIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteContentByContentBbIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteContentByContentBbIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void getContentTocDetailsForGivenCourseCompletedEventHandler(object sender, getContentTocDetailsForGivenCourseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getContentTocDetailsForGivenCourseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getContentTocDetailsForGivenCourseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public stringArray[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((stringArray[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void getChildContentFromParentContentBbIdCompletedEventHandler(object sender, getChildContentFromParentContentBbIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getChildContentFromParentContentBbIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getChildContentFromParentContentBbIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public stringArray[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((stringArray[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void getContentDetailsFromContentBbIdCompletedEventHandler(object sender, getContentDetailsFromContentBbIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getContentDetailsFromContentBbIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getContentDetailsFromContentBbIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public stringArray[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((stringArray[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void getFileDetailsFromContentBbIdCompletedEventHandler(object sender, getFileDetailsFromContentBbIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getFileDetailsFromContentBbIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getFileDetailsFromContentBbIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public stringArray[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((stringArray[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591