//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bbIDLA.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://idlatestbb.com:80/webapps/IDLA-BbWebservices-BB_bb60/BBCourseWebService")]
        public string bbIDLA_BBCourseWebService_BBCourseWebService {
            get {
                return ((string)(this["bbIDLA_BBCourseWebService_BBCourseWebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://idlatestbb.com:80/webapps/IDLA-BbWebservices-BB_bb60/BBUserWebService")]
        public string bbIDLA_BBUserService_BBUserWebService {
            get {
                return ((string)(this["bbIDLA_BBUserService_BBUserWebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://idlatestbb.com:80/webapps/IDLA-BbWebservices-BB_bb60/BBGradebookWebService" +
            "")]
        public string bbIDLA_BBGradebookService_BBGradebookWebServiceService {
            get {
                return ((string)(this["bbIDLA_BBGradebookService_BBGradebookWebServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://idlatestbb.com:80/webapps/IDLA-BbWebservices-BB_bb60/BbWebservices")]
        public string bbIDLA_BBAddedService_BbWebservices {
            get {
                return ((string)(this["bbIDLA_BBAddedService_BbWebservices"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://idlatestbb.com:80/webapps/IDLA-BbWebservices-BB_bb60/BBAnnouncementsWebSer" +
            "vice")]
        public string bbIDLA_BBAnnouncementService_BBAnnouncementsWebService {
            get {
                return ((string)(this["bbIDLA_BBAnnouncementService_BBAnnouncementsWebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://idlatestbb.com:80/webapps/IDLA-BbWebservices-BB_bb60/BBCalendarWebService")]
        public string bbIDLA_BBCalendarService_BBCalendarWebService {
            get {
                return ((string)(this["bbIDLA_BBCalendarService_BBCalendarWebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://idlatestbb.com:80/webapps/IDLA-BbWebservices-BB_bb60/BBContentWebService")]
        public string bbIDLA_BBContentService_BBContentWebService {
            get {
                return ((string)(this["bbIDLA_BBContentService_BBContentWebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://idlatestbb.com:80/webapps/IDLA-BbWebservices-BB_bb60/BBDiscussionBoardWebS" +
            "ervice")]
        public string bbIDLA_BBDiscussionBoardService_BBDiscussionBoardWebServiceService {
            get {
                return ((string)(this["bbIDLA_BBDiscussionBoardService_BBDiscussionBoardWebServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://idlatestbb.com:80/webapps/IDLA-BbWebservices-BB_bb60/BBGroupWebService")]
        public string bbIDLA_BBGroupService_BBGroupWebServiceService {
            get {
                return ((string)(this["bbIDLA_BBGroupService_BBGroupWebServiceService"]));
            }
        }
    }
}
